name: Snyk Code Scan

on: 
  workflow_dispatch:

jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Optionally add path to checkout to a specific subdirectory
        # with:
        #   path: some-subfolder

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        with: 
          command: code test
          args: --sarif-file-output=snyk_code_scan.sarif --severity-threshold=high 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SARIF file to GitHub Security tab
        if: success() || failure() # Upload even if Snyk finds issues
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_code_scan.sarif
